### ISSUE TITLE
Document how to enable IP forwarding

### ISSUE THREAD

**Issue by bondehagen** [tailscale/tailscale-synology#52]
Did anyone got this working? If so, it should be added to documentation.

**Comment by StarTech42** [comment]
Yes, sort of... I followed the Zero Tier manual to edit the IPtables (with only Tailscale installed, no Zero Tier)- [https://zerotier.atlassian.net/wiki/spaces/SD/pages/224395274/Route+between+ZeroTier+and+Physical+Networks](url)
So SSH'd in and this code worked with my DSM 6:

`PHY_IFACE=eth0; ZT_IFACE=eth50

sudo iptables -t nat -A POSTROUTING -o $PHY_IFACE -j MASQUERADE
sudo iptables -A FORWARD -i $PHY_IFACE -o $ZT_IFACE -m state --state RELATED,ESTABLISHED -j ACCEPT
sudo iptables -A FORWARD -i $ZT_IFACE -o $PHY_IFACE -j ACCEPT`

However, DSM doesn't allow the IPtables to become persistant using the usual Linux commands, so it's certainly reset after a reboot, and it was suggested that the system could possibly over write them on the fly.

Whilst this worked for me with DSM 6, I'm not sure how it'll do on DSM 7.
