### ISSUE TITLE
1.8.3 32-bit ARM segfault due to unaligned atomic access

### ISSUE THREAD

**Issue by bogsen** [tailscale/tailscale-synology#66]
**Description**
Tailscale segfaults on 32-bit ARM, due to unaligned atomic access in inet.af/netstack. Seems to have been fixed upstream in https://github.com/google/gvisor/issues/5692; I've tested a manual build with the fixes included and it does seem to work fine.

**Steps to reproduce**
Install Tailscale package, do `tailscale up`

**Expected behavior**
Tailscale should not segfault

**Synology NAS model**
DS218j

**Comment by DentonGentry** [comment]
I moved this to https://github.com/tailscale/tailscale/issues/2129 where it is easier for us to track and prioritize with the other platforms.

**Comment by bradfitz** [comment]
@DentonGentry, rather than mirror bugs, we can transfer them. In the bottom of the right sidebar:

<img width="213" alt="Screen Shot 2021-06-22 at 9 57 18 AM" src="https://user-images.githubusercontent.com/2621/122968291-3bd34000-d340-11eb-9c12-b2abe601060e.png">
